"""initial schema

Revision ID: 4864c0fa0754
Revises: 
Create Date: 2026-09-25 01:16:30.380102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.encryption

# revision identifiers, used by Alembic.
revision: str = '4864c0fa0754'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_credit_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_number', sa.String(), nullable=False),
    sa.Column('pull_type', sa.Enum('soft_pull', 'hard_pull', name='credit_pull_type'), nullable=False),
    sa.Column('experian_score', sa.Integer(), nullable=True),
    sa.Column('equifax_score', sa.Integer(), nullable=True),
    sa.Column('transunion_score', sa.Integer(), nullable=True),
    sa.Column('middle_score', sa.Integer(), nullable=False),
    sa.Column('tradelines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_insurance_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('annual_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('provider_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('metro', sa.String(), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('baths', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('sqft', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.Enum('single_family', 'two_to_four_unit', 'condo', 'townhome', name='property_type'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('deal_grade', sa.Enum('great_buy', 'good_buy', name='deal_grade'), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_los_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_number', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_number')
    )
    op.create_table('provider_rate_sheet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investor_name', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('program', sa.Enum('conventional', 'dscr', name='rate_sheet_program'), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('min_fico', sa.Integer(), nullable=False),
    sa.Column('max_ltv', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dscr_bucket', sa.String(), nullable=True),
    sa.Column('ppp_years', sa.Integer(), nullable=True),
    sa.Column('str_only', sa.Boolean(), nullable=False),
    sa.Column('lead_source', sa.String(), nullable=True),
    sa.Column('lock_days', sa.Integer(), nullable=False),
    sa.Column('fico_adjustment_bps', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ltv_adjustment_bps', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_rents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('market_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comps_count', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_str_revenue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occupancy_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('adr', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('comps_count', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_tax_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('annual_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county', 'state')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('lo', 'manager', 'admin', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('nmls', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('assigned_lo_id', sa.UUID(), nullable=False),
    sa.Column('crm_contact_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_lo_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_assigned_lo_id'), 'clients', ['assigned_lo_id'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('lo_id', sa.UUID(), nullable=False),
    sa.Column('los_loan_guid', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('intake', 'verifying', 'needs_attention', 'ready_to_price', 'priced', 'sent', 'viewed', 'option_selected', 'inquiry', 'stale', 'withdrawn', 'closed', name='application_status'), nullable=False),
    sa.Column('occupancy', sa.Enum('primary', 'investment', name='occupancy'), nullable=False),
    sa.Column('strategy', sa.Enum('ltr', 'str', name='strategy'), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('purpose', sa.Enum('purchase', name='loan_purpose'), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subject_state', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['lo_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('los_loan_guid')
    )
    op.create_index(op.f('ix_applications_client_id'), 'applications', ['client_id'], unique=False)
    op.create_index(op.f('ix_applications_lo_id'), 'applications', ['lo_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_subject_state'), 'applications', ['subject_state'], unique=False)
    op.create_table('borrower_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_accounts_client_id'), 'borrower_accounts', ['client_id'], unique=True)
    op.create_index(op.f('ix_borrower_accounts_email'), 'borrower_accounts', ['email'], unique=True)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_application_id'), 'activity_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_activity_events_at'), 'activity_events', ['at'], unique=False)
    op.create_table('application_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('borrower', 'co_borrower', name='party_role'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('ssn_encrypted', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.Enum('married', 'unmarried', 'separated', name='marital_status'), nullable=True),
    sa.Column('dependents_count', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cell_phone', sa.String(), nullable=True),
    sa.Column('home_phone', sa.String(), nullable=True),
    sa.Column('work_phone', sa.String(), nullable=True),
    sa.Column('business_vesting', sa.Enum('title_lien_in_llc', 'personal_name', name='business_vesting'), nullable=True),
    sa.Column('llc_entity_name', sa.String(), nullable=True),
    sa.Column('no_co_applicant_check', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'role')
    )
    op.create_index(op.f('ix_application_parties_application_id'), 'application_parties', ['application_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('verified_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_application_id'), 'assets', ['application_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('hard_pull', name='consent_type'), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_application_id'), 'consents', ['application_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_table('field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('encompass', 'rentcast', 'airdna', 'smartasset', 'steadily', 'optimal_blue', 'credit_bureau', 'property_search', 'lo_entry', 'formula', 'default', 'lo_override', name='field_source'), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'field_key')
    )
    op.create_index(op.f('ix_field_values_application_id'), 'field_values', ['application_id'], unique=False)
    op.create_index(op.f('ix_field_values_field_key'), 'field_values', ['field_key'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('tab', sa.Enum('borrowers', 'housing', 'credit', 'assets', 'property', 'pricing', 'send', name='application_tab'), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'blocking', name='flag_severity'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_application_id'), 'flags', ['application_id'], unique=False)
    op.create_index('ix_flags_application_id_resolved_at', 'flags', ['application_id', 'resolved_at'], unique=False)
    op.create_table('housing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('housing_status', sa.Enum('own', 'rent', 'rent_free', name='housing_status'), nullable=False),
    sa.Column('residence_years', sa.Integer(), nullable=False),
    sa.Column('residence_months', sa.Integer(), nullable=False),
    sa.Column('vom_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_history_application_id'), 'housing_history', ['application_id'], unique=False)
    op.create_table('integration_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adapter', sa.String(), nullable=False),
    sa.Column('request_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_calls_application_id'), 'integration_calls', ['application_id'], unique=False)
    op.create_index(op.f('ix_integration_calls_called_at'), 'integration_calls', ['called_at'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('creditor_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liabilities_application_id'), 'liabilities', ['application_id'], unique=False)
    op.create_table('outbox_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('attachment_keys', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='email_status'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_emails_application_id'), 'outbox_emails', ['application_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('address_status', sa.Enum('specific_address', 'tbd', name='property_address_status'), nullable=False),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('property_type', sa.Enum('single_family', 'two_to_four_unit', 'condo', 'townhome', name='property_type'), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('buy_box_states', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('buy_box_metros', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('recommend_matches', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dscr_bucket', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_application_id'), 'scenarios', ['application_id'], unique=False)
    op.create_table('employment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('years_at_job', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('self_employed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['application_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_application_id'), 'employment', ['application_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('investor', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('lock_days', sa.Integer(), nullable=False),
    sa.Column('computed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('priced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_scenario_id'), 'quotes', ['scenario_id'], unique=False)
    op.create_table('quote_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('quote_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('recommended_quote_id', sa.UUID(), nullable=True),
    sa.Column('lo_note', sa.Text(), nullable=True),
    sa.Column('letter_key', sa.String(), nullable=True),
    sa.Column('report_token', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('borrower_action', sa.Enum('option_selected', 'inquiry', name='borrower_action'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['recommended_quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_packages_application_id'), 'quote_packages', ['application_id'], unique=False)
    op.create_index(op.f('ix_quote_packages_report_token'), 'quote_packages', ['report_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_packages_report_token'), table_name='quote_packages')
    op.drop_index(op.f('ix_quote_packages_application_id'), table_name='quote_packages')
    op.drop_table('quote_packages')
    op.drop_index(op.f('ix_quotes_scenario_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_employment_application_id'), table_name='employment')
    op.drop_table('employment')
    op.drop_index(op.f('ix_scenarios_application_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('properties')
    op.drop_index(op.f('ix_outbox_emails_application_id'), table_name='outbox_emails')
    op.drop_table('outbox_emails')
    op.drop_index(op.f('ix_liabilities_application_id'), table_name='liabilities')
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_integration_calls_called_at'), table_name='integration_calls')
    op.drop_index(op.f('ix_integration_calls_application_id'), table_name='integration_calls')
    op.drop_table('integration_calls')
    op.drop_index(op.f('ix_housing_history_application_id'), table_name='housing_history')
    op.drop_table('housing_history')
    op.drop_index('ix_flags_application_id_resolved_at', table_name='flags')
    op.drop_index(op.f('ix_flags_application_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_field_values_field_key'), table_name='field_values')
    op.drop_index(op.f('ix_field_values_application_id'), table_name='field_values')
    op.drop_table('field_values')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_consents_application_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_assets_application_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_application_parties_application_id'), table_name='application_parties')
    op.drop_table('application_parties')
    op.drop_index(op.f('ix_activity_events_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_application_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_borrower_accounts_email'), table_name='borrower_accounts')
    op.drop_index(op.f('ix_borrower_accounts_client_id'), table_name='borrower_accounts')
    op.drop_table('borrower_accounts')
    op.drop_index(op.f('ix_applications_subject_state'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_lo_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_client_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('settings')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_assigned_lo_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('provider_tax_rates')
    op.drop_table('provider_str_revenue')
    op.drop_table('provider_rents')
    op.drop_table('provider_rate_sheet')
    op.drop_table('provider_los_records')
    op.drop_table('provider_listings')
    op.drop_table('provider_insurance_factors')
    op.drop_table('provider_credit_reports')
    op.drop_table('crm_events')
    # ### end Alembic commands ###

    # Alembic's autogenerated `drop_table` calls above don't also drop the
    # native Postgres enum types the dropped columns used (unlike
    # `Base.metadata.drop_all()`, which tracks that) — without this, a
    # second `upgrade head` after `downgrade base` fails with
    # `type "..." already exists` on the first CREATE TYPE. Drop every enum
    # type this revision created, now that no column references it.
    for enum_name in (
        "user_role",
        "application_status",
        "occupancy",
        "strategy",
        "loan_purpose",
        "field_source",
        "application_tab",
        "flag_severity",
        "party_role",
        "marital_status",
        "business_vesting",
        "housing_status",
        "property_address_status",
        "property_type",
        "borrower_action",
        "consent_type",
        "email_status",
        "rate_sheet_program",
        "deal_grade",
        "credit_pull_type",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
