"""quote_packages recommendation_text

Revision ID: 5bd9d8620699
Revises: e419a34bcdbd
Create Date: 2026-09-25 13:02:29.017977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bd9d8620699"
down_revision: Union[str, None] = "e419a34bcdbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quote_packages", sa.Column("recommendation_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote_packages", "recommendation_text")
    # ### end Alembic commands ###
