"""p3p4 foundation

P3/P4 foundation unit (docs/backlog/phase-p3-p4-foundation.md, plan.md
Decision D1): the one shared migration every P3 (CQ-016-020) and P4
(CQ-021-024) item was predicted to need, landed once up front so parallel
worker worktrees never fork `alembic heads`.

- `applications.last_pipeline_stage` (nullable `String`): CQ-016's pipeline
  activities write the current Temporal stage name here so the workspace
  summary can poll status without reaching into Temporal itself.
- `applications.recommended_quote_id` (nullable, indexed FK ->
  `quotes.id`, `ON DELETE SET NULL`): CQ-018 sets the one recommended
  quote per application. Added with `use_alter=True` / a separate `ALTER
  TABLE ... ADD CONSTRAINT` because `applications -> quotes` (via this FK)
  and `quotes -> scenarios -> applications` (via `quotes.scenario_id` /
  `scenarios.application_id`) would otherwise be a foreign-key cycle that
  neither `Base.metadata`'s topological sort nor a single `CREATE
  TABLE`/`ALTER TABLE` list can express in one pass.
- `quotes.stale` (`Boolean NOT NULL DEFAULT false`): CQ-017 sets this when
  a field-value override/revert changes an input a quote was priced from.
- `quote_package_versions`: the frozen, sent snapshot of a `quote_packages`
  row (plan.md Decision D2 -- `quote_packages` stays the draft/working
  package; this table holds what was actually emailed, one row per send).
  CQ-020 writes rows here; CQ-022 (borrower report) and CQ-024 (borrower
  actions) read them by `report_token`, which is opaque and only *selects*
  a version -- it is never itself a credential (plan.md H2).

Revision ID: bbd0e3150264
Revises: 642b3bc55d31
Create Date: 2026-09-25 07:00:40.603296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbd0e3150264'
down_revision: Union[str, None] = '642b3bc55d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_package_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('letter_key', sa.String(), nullable=True),
    sa.Column('report_token', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('borrower_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['quote_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'version')
    )
    op.create_index(op.f('ix_quote_package_versions_package_id'), 'quote_package_versions', ['package_id'], unique=False)
    op.create_index(op.f('ix_quote_package_versions_report_token'), 'quote_package_versions', ['report_token'], unique=True)
    op.add_column('applications', sa.Column('last_pipeline_stage', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('recommended_quote_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_applications_recommended_quote_id'), 'applications', ['recommended_quote_id'], unique=False)
    op.create_foreign_key('fk_applications_recommended_quote_id', 'applications', 'quotes', ['recommended_quote_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('quotes', sa.Column('stale', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'stale')
    op.drop_constraint('fk_applications_recommended_quote_id', 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_recommended_quote_id'), table_name='applications')
    op.drop_column('applications', 'recommended_quote_id')
    op.drop_column('applications', 'last_pipeline_stage')
    op.drop_index(op.f('ix_quote_package_versions_report_token'), table_name='quote_package_versions')
    op.drop_index(op.f('ix_quote_package_versions_package_id'), table_name='quote_package_versions')
    op.drop_table('quote_package_versions')
    # ### end Alembic commands ###
