"""quote_packages lo_edited

Revision ID: c8869567cd57
Revises: 5bd9d8620699
Create Date: 2026-09-25 15:57:28.827679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8869567cd57'
down_revision: Union[str, None] = '5bd9d8620699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote_packages",
        sa.Column("lo_edited", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote_packages", "lo_edited")
    # ### end Alembic commands ###
