"""provider_listings county and str_permitted

Revision ID: e419a34bcdbd
Revises: bbd0e3150264
Create Date: 2026-09-25 09:24:52.996223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e419a34bcdbd"
down_revision: Union[str, None] = "bbd0e3150264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider_listings",
        sa.Column("county", sa.String(), server_default=sa.text("''"), nullable=False),
    )
    op.add_column(
        "provider_listings",
        sa.Column("str_permitted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_listings", "str_permitted")
    op.drop_column("provider_listings", "county")
    # ### end Alembic commands ###
