"""`support_requests` table (P5/P6 foundation, E1; CQ-034 owns the
endpoint, the reference format and the emails)."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class SupportRequest(Base):
    """Append-only: one row per submitted support form."""

    __tablename__ = "support_requests"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    reference: Mapped[str] = mapped_column(String(16), unique=True)
    """Short human reference, e.g. `SUP-7F3K2` (generated by CQ-034)."""
    borrower_account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("borrower_accounts.id", ondelete="CASCADE"), index=True
    )
    application_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("applications.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    """The borrower's latest application at submit time; `None` when they
    have none (CQ-034 AC5)."""
    topic: Mapped[str] = mapped_column(String)
    """`application` / `quote` / `documents` / `other` (validated by CQ-034)."""
    message: Mapped[str] = mapped_column(Text)
    preferred_contact: Mapped[str] = mapped_column(String)
    """`email` or `phone` (validated by CQ-034)."""
    phone: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
